# This is a basic workflow to help you get started with Actions

name: C-Integration

on:
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # add more test files here
        files:
          - src/test/test1.test.js
          - src/test/test2.test.js
          - src/test/test3.test.js

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      # cache node modules to prevent repeated downloading of library
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # install dependencies
      - name: npm install
        run: yarn install --immutable --immutable-cache --check-cache

      # start testing. matrix files is supplied from strategy matrix above
      - name: test to test integration
        run: yarn test ${{ matrix.files }}
