# This is a basic workflow to help you get started with Actions

name: C-Integration

on:
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # install dependencies
      - name: npm install
        run: yarn install

      # start testing
      - name: test to test integration
        run: >
          yarn test
          src/test/test1.test.js
          src/test/test2.test.js
          src/test/test3.test.js
          src/test/test4.test.js
