# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14

      - name: Run npm install
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test to test integration
        run: yarn test
        
      - name: Run build to test it compiled properly
        run: yarn build
